#!/bin/sh

MODE=$1   # pass "dark" or "light" when running the script

if [ "$MODE" = "dark" ]; then
    wall=~/pix/dds/digital-art-boy-dark.jpg
    xwallpaper --zoom "$wall"

    wal -c
    wal --theme /home/zephyr/.local/bin/pywal/dist/rose-pine-main.json

elif [ "$MODE" = "light" ]; then
    wall=~/pix/dds/digital-art-boy-light.jpg
    xwallpaper --zoom "$wall"

    wal -c
    wal --theme /home/zephyr/.local/bin/pywal/dist/rose-pine-dawn.json
fi

# Refresh the status bar
xdotool key super+F5

# Dvorak remap
xmodmap-dvorak &

